#!/bin/sh

# Simple script to apply the ssh keys to right location in the home directory

if [ ! -d /home/bob/.ssh ] ; then
 mkdir /home/bob/.ssh
 echo "Create the ~/.ssh directory"
fi


if [ ! -f /home/bob/.ssh/id_rsa ] ; then
echo $ID_RSA_KEY | base64 -d >  /home/bob/.ssh/id_rsa
 # echo $ID_RSA_KEY >  /home/bob/.ssh/id_rsa
 chmod 600 /home/bob/.ssh/id_rsa
 echo "Create the ssh key"
fi

if [ ! -f ~/.ssh/id_rsa.pub ] ; then
 echo $ID_RSA_KEY_PUB | base64 -d > /home/bob/.ssh/id_rsa.pub
 # echo $ID_RSA_KEY_PUB > /home/bob/.ssh/id_rsa.pub
 chmod 600 /home/bob/.ssh/id_rsa.pub
 echo "Create the public ssh key"
fi

DEFAULT_SLEEP=5400
if [ ! -z $1 ] ; then
 DEFAULT_SLEEP=$1
fi
echo "Default sleep time: $DEFAULT_SLEEP seconds"
/bin/sleep $DEFAULT_SLEEP
