#!/bin/sh

# Simple blocking script for the build container to execute.  Default is set for 30minutes beyond the Drone pipeline timeout.

if [ ! -d /home/bob/.ssh ] ; then
 mkdir /home/bob/.ssh
fi

if [ ! -z $ID_RSA_KEY ] ; then
 if [ ! -f /home/bob/.ssh/id_rsa ] ; then
  cat $ID_RSA_KEY >  /home/bob/.ssh/id_rsa
  chmod 600 /home/bob/.ssh/id_rsa
 fi
fi

if [ ! -z $ID_RSA_KEY_PUB ] ; then
 if [ ! -f ~/.ssh/id_rsa.pub ] ; then
  cat $ID_RSA_KEY_PUB > /home/bob/.ssh/id_rsa.pub
  chmod 600 /home/bob/.ssh/id_rsa.pub
 fi
fi

DEFAULT_SLEEP=5400
if [ ! -z $1 ] ; then
 DEFAULT_SLEEP = $1
fi
/bin/sleep $DEFAULT_SLEEP
