kind: pipeline
type: kubernetes
name: Continuous Integration

steps:
- name: Local Build - aarch64
  image: docker.io/gautada/builder:3.2.3-r1-aarch64
  privileged: true
  environment:
    DOCKER_USERNAME:
      from_secret: username.docker.io
    DOCKER_PASSWORD:
      from_secret: password.docker.io
    PODMAN_x86_64_USERNAME:
      from_secret: username.docker.io
    PODMAN_x86_64_PASSWORD:
      from_secret: password.docker.io
    ALPINE_TAG: 3.14.2
    OCI_VERSION: 3.2.3-r1
    OCI_CONTAINER: builder
    OCI_REPOSITORY: docker://docker.io/gautada
    OCI_CPU: aarch64
  commands:
  - buildah login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD docker.io
  - buildah bud --build-arg ALPINE_TAG=$ALPINE_TAG --build-arg VERSION=$OCI_VERSION --file Containerfile --no-cache --tag localhost/$OCI_CONTAINER:dev
  - buildah push localhost/$OCI_CONTAINER:dev $OCI_REPOSITORY/$OCI_CONTAINER:$OCI_VERSION-$OCI_CPU
- name: Podman Remote Build - x86_64
  image: docker.io/gautada/builder:3.2.3-r1-aarch64
  privileged: true
  environment:
    DOCKER_USERNAME:
      from_secret: username.docker.io
    DOCKER_PASSWORD:
      from_secret: password.docker.io
    ID_RSA_KEY:
      from_secret: podman.ssh.key
    ID_RSA_KEY_PUB:
      from_secret: podman.ssh.pkey
    ALPINE_TAG: 3.14.2
    OCI_VERSION: 3.2.3-r1
    OCI_CONTAINER: builder
    OCI_REPOSITORY: docker://docker.io/gautada
    OCI_CPU: x86_64
  commands:
  - ./builder-base 5
  - ssh -o "StrictHostKeyChecking=no" -i /home/bob/.ssh/id_rsa bob@x86-builder.cicd.svc.cluster.local /bin/sleep 5
  - podman --remote --connection x86_64 login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD docker.io
  - podman --remote --connection x86_64 build --build-arg ALPINE_TAG=$ALPINE_TAG --build-arg VERSION=$OCI_VERSION --file Containerfile --no-cache --tag localhost/$OCI_CONTAINER:dev .
  - podman --remote --connection x86_64 push localhost/$OCI_CONTAINER:dev $OCI_REPOSITORY/$OCI_CONTAINER:$OCI_VERSION-x86_64
  # podman --remote manifest create $OCI_REPOSITORY/$OCI_CONTAINER:$OCI_VERSION
  # podman --remote manifest add $OCI_REPOSITORY/$OCI_CONTAINER:$OCI_VERSION $OCI_REPOSITORY/$OCI_CONTAINER:$OCI_VERSION-aarch64
  # podman --remote manifest add $OCI_REPOSITORY/$OCI_CONTAINER:$OCI_VERSION $OCI_REPOSITORY/$OCI_CONTAINER:$OCI_VERSION-x86_64

trigger:
  branch:
  - dev


