kind: pipeline
type: kubernetes
name: Continuous Integration

steps:
- name: integrate
  image: gautada/builder:v1.21.4_v3.2.3
  privileged: true
  environment:
    DOCKER_USERNAME:
      from_secret: username.docker.io
    DOCKER_PASSWORD:
      from_secret: password.docker.io
    ALPINE_TAG: 3.14.1
    OCI_VERSION: v1.21.4_v3.2.3
    OCI_OS: linux
    OCI_ARCH: arm64
  commands:
  - buildah login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD docker.io
  - buildah bud --build-arg ALPINE_TAG=$ALPINE_TAG --tag localhost/builder:dev -f Containerfile
  - buildah push localhost/builder:dev docker://docker.io/gautada/builder:$OCI_VERSION
  
trigger:
  branch:
  - main


