kind: pipeline
type: kubernetes
name: Continuous Integration

steps:
- name: arm-build
  image: docker.io/gautada/builder:arm-3.2.3-r1
  privileged: true
  environment:
    PODMAN_KEY:
      from_secret: podman.key
    PODMAN_CERT:
      from_secret: podman.cert
    ALPINE_TAG: "3.14.2"
    PODMAN_VERSION: "3.2.3-r1"
  commands:
  - /builder-base 5
  - podman --remote --connection arm build --build-arg ALPINE_TAG=$ALPINE_TAG --build-arg VERSION=$PODMAN_VERSION --file Containerfile --format docker --no-cache --platform linux/arm64/v8 --tag builder:dev .

- name: x86-build
  image: docker.io/gautada/builder:arm-3.2.3-r1
  privileged: true
  environment:
    PODMAN_KEY:
      from_secret: podman.key
    PODMAN_CERT:
      from_secret: podman.cert
    ALPINE_TAG: "3.14.2"
    PODMAN_VERSION: "3.2.3-r1"
  commands:
  - /builder-base 5
  - podman --remote --connection x86 build --build-arg ALPINE_TAG=$ALPINE_TAG --build-arg VERSION=$PODMAN_VERSION --file Containerfile --format docker --no-cache --platform linux/amd64 --tag builder:dev .
  

trigger:
  branch:
  - dev


