kind: pipeline
type: kubernetes
name: Continuous Integration

steps:
- name: Build (aarch64)
  image: docker.io/gautada/builder:3.2.3-r1-aarch64
  privileged: true
  environment:
    DOCKER_USERNAME:
      from_secret: username.docker.io
    DOCKER_PASSWORD:
      from_secret: password.docker.io
    ALPINE_TAG: 3.14.2
    OCI_VERSION: 3.2.3-r1
    OCI_CONTAINER: builder
    OCI_REPOSITORY: docker://docker.io/gautada
    OCI_CPU: aarch64
  commands:
  # /builder-base 5
  - ls -l
  - ls -l /
  - whoami
  - podman --remote --connection x86_64 run docker.io/hello-world
  # - buildah login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD docker.io
  # - buildah bud --build-arg ALPINE_TAG=$ALPINE_TAG --build-arg VERSION=$OCI_VERSION --file Containerfile --no-cache --tag localhost/$OCI_CONTAINER:dev
  # - buildah push localhost/$OCI_CONTAINER:dev $OCI_REPOSITORY/$OCI_CONTAINER:$OCI_VERSION-$OCI_CPU
  
trigger:
  branch:
  - main


