apiVersion: v1
kind: Pod
metadata:
 name: bob
spec:
 containers:
   - name: bob
     image: gautada/builder:v1.21.4_v3.2.3
     imagePullPolicy: Always
     securityContext:
       privileged: true
     volumeMounts:
       - mountPath: /var/lib/containers/storage/overlay
         name: podman-local
 volumes:
   - name: podman-local
     hostPath:
       path: /var/lib/containers/storage/overlay
